telegram.bot.name=java_learning_2026_bot
telegram.bot.token=8406165008:AAHopDZ5W86rXsxsyGHEgkQTUXAI2U9OkMg
app.version=1.0.0
app.url=https://example.com/api
app.timeout=5000

spring.config.location=optional:file:./dev/config/*/